Bilfirman/Models/Agreement.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bilfirman.Models
{
    public class Agreement
    {
        public int Id { get; set; }
        public DateTime From { get; set; }
        public DateTime To { get; set; }
        public Car Car { get; set; }
        public Customer Customer { get; set; }
    }
}

Bilfirman/Models/Car.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bilfirman.Models
{
    public class Car
    {
        public string Registration { get; set; }
        public string Model { get; set; } //Leaf, 3, i3
        public string Manufacturer { get; set; } //Nissan, Tesla, BMW
        public string Color { get; set; } //Red, Pink, Blue
        public bool Rented { get; set; }
    }
}

Bilfirman/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bilfirman.Models
{
    public class Customer
    {
        public string Name { get; set; }
        public int Phone { get; set; }
        public int Id { get; set; }
        public int License { get; set; }
    }
}

Bilfirman/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bilfirman.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            int hour = DateTime.Now.Hour;
            ViewBag.Greeting = hour < 12 ? "Good morning" : "Good afternoon";
            return View();
        }

        public ActionResult Rent()
        {
            return View();
        }
    }
}

Bilfirman/Controllers/RentalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bilfirman.Models;

namespace Bilfirman.Controllers
{
    public class RentalController : Controller
    {
        private List<Car> cars;
        private List<Customer> customers;

        public RentalController()
        {
            cars = new List<Car>();
            cars.Add(new Car() { Registration = "AVD125", Model = "i3", Manufacturer = "BMW", Color = "Green", Rented=true});
            cars.Add(new Car() { Registration = "BFC591", Model = "Leaf", Manufacturer = "Nissan", Color = "Pink", Rented = false });
            cars.Add(new Car() { Registration = "HDE146", Model = "3", Manufacturer = "Tesla", Color = "Red", Rented = false});

            customers = new List<Customer>();
            customers.Add(new Customer() { Name = "Christer" });
        }

        // GET: Rental
        public ActionResult Index()
        {
            return View(cars);
        }

        public ActionResult Cars()
        {
            return PartialView("_Cars", cars);
        }

        public ViewResult  Details (string Registration)
        {
            return View("CarDetails", cars.First(x => x.Registration == Registration));
        }

        public PartialViewResult Customers()
        {
            return PartialView("_Customers", customers);
        }

        
    }
}

Bilfirman/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<div>
    @ViewBag.Greeting
</div>

Bilfirman/Views/Rental/CarDetails.cshtml
@model Bilfirman.Models.Car
    <div>
        <h3>@Model.Manufacturer @Model.Model </h3>
        Colour: @Model.Color <br />
        Registration: @Model.Registration

        <br />
        @if (Model.Rented == true)
        {
            Write("Car is rented at the moment");
        }
        else
        {
            @Html.ActionLink("Rent here!", "Index", "Rental");
        }
    </div>
    <div>
        @Html.ActionLink("Back", "Index")
    </div>

Bilfirman/Views/Rental/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Rent a car here!</h2>

<div>
    @{ 
        Html.RenderAction("cars");
    }
</div>
<div>
    @{ 
        Html.RenderAction("Customers");
    }
</div>

Bilfirman/Views/Rental/_Cars.cshtml
@model List<Bilfirman.Models.Car>

<ul>
    @foreach (var item in Model)
    {

        <li>@if (item.Manufacturer == "BMW")
        {
            <img class="carpic" src="~/Content/bmw.jpg"/>
        }
        else if (item.Manufacturer == "Tesla")
        {
            <img class="carpic" src="~/Content/tesla.jpg" />
        }
        else if (item.Manufacturer == "Nissan")
        {
            <img class="carpic" src="~/Content/nissan.jpg" />
        }
             @item.Manufacturer @item.Model | @Html.ActionLink("Info", "Details", new { Registration = item.Registration })</li>
    }

</ul>

Bilfirman/Views/Rental/_Customers.cshtml
@model List<Bilfirman.Models.Customer>
    <ul>
        @foreach (var item in Model)
        {
            <li>@item.Name</li>
        }
    </ul>

Bilfirman/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/Main.css" rel="stylesheet" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="header">
        <div class="btn btn-default">
            @Html.ActionLink("Home", "Index","Home")
        </div>
        <div class="btn btn-default">
            @Html.ActionLink("Rent a car", "Index", "Rental")
        </div>
            
        
    </div>
    @RenderBody()
</body>
</html>